# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u677f\u5757\u540d\u79f0')),
                ('desc', models.CharField(max_length=100, verbose_name='\u677f\u5757\u63cf\u8ff0')),
                ('manager_name', models.CharField(max_length=100, verbose_name='\u677f\u5757\u7ba1\u7406\u5458\u540d\u79f0')),
            ],
        ),
    ]
