# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-15 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'verbose_name': '\u7248\u5757', 'verbose_name_plural': '\u7248\u5757'},
        ),
        migrations.AddField(
            model_name='block',
            name='status',
            field=models.IntegerField(choices=[(0, b'\xe6\xad\xa3\xe5\xb8\xb8'), (-1, b'\xe5\x88\xa0\xe9\x99\xa4')], default=0, verbose_name='\u72b6\u6001'),
            preserve_default=False,
        ),
    ]
